apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          # Original image reference that will pass OPA Gatekeeper validation
          image: myapp:latest
          
          # Uncomment below and comment out the line above to trigger OPA Gatekeeper validation failure (unauthorized registry)
          # image: docker.io/library/python:3.9-slim
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.25"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
