apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: myapp
    newName: europe-west1-docker.pkg.dev/cmpe-58e-term-project/myapp-repo/myapp
    newTag: latest