apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: only-allow-project-registry
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces:
      - "default"
  parameters:
    repos:
      # This is the allowed registry pattern
      - "europe-west1-docker.pkg.dev/cmpe-58e-term-project/myapp-repo/"
