name: DevSecOps Pipeline

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.9'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pylint pytest
            
            - name: Lint code
              run: pylint app/

            - name: Run tests
              run: pytest


    # Needs more research on how to implement the best
    security-scan:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

    #         - name: Run SAST with CodeQL
    #           uses: github/codeql-action/analyze@v2

    #         - name: Run Secret Scanning
    #           uses: github/secret-scanning@v1 

    build-image:
        needs: security-scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build Docker Image
              run: docker build -t myapp:${{ github.sha}} .

            - name: Run container scan with Trivy
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: myapp:${{ github.sha}}
                format: 'sarif'
                output: "trivy-results.sarif"

            - name: Upload Trivy scan results to Github Security tab
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: trivy-results.sarif

            
